project_id = "xdjyejuddhopsjhltdri"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-visibility-payment]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.mpk-proxy]
verify_jwt = false
